name: 'dbt_surrogate_key_utils'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

# CRITICAL: This makes your macro override dbt_utils
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_surrogate_key_utils', 'dbt_utils']

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"